name: ubuntu-vnc-docker-build-and-push-extended

on:
  push:
    branches:
      - 'main'

    tags:
      - 'v*'

    paths-ignore:
      - "LICENSE"
      - "ARCHITECTURE.md"
      - "README.md"
  
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "ARCHITECTURE.md"
      - "README.md"

  workflow_dispatch:

jobs:
  buildAndPublishDockerImage:
    name: Build and publish ubuntu workspace novnc image extended
    runs-on: ubuntu-20.04
    steps:

      - name: Print Github event context
        env: 
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=sha

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image with sha tag
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}-extended , ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest-extended
          # Do not push on pull request trigger - only build
          push:  ${{ github.event_name != 'pull_request' }}
